### ISSUE TITLE
Separate `setup_model_and_dataset` into two functions

### ISSUE THREAD

**Issue by drewoldag** [lincc-frameworks/fibad#128]
Currently setup_model_and_dataset does exactly what is says, but this is somewhat wasteful in most cases. It would be better to separate this into two distinct functions in pytorch_ignite.py:
```
def setup_dataset(config, split) - > data_set:
    data_set_cls = fetch_data_set_class(config)
    data_set = data_set_cls(config, split)
    return data_set

def setup_model(config, data_set) -> model:
    model_cls = fetch_model_class(config)
    model = model_cls(config, data_set.shape())
    return model
```

Then in `train.py` for instance: 
```
train_data_set = setup_dataset(config, "train")
model = setup_model(config, train_data_set)
validation_data_set = setup_dataset(config, "validate")
...
```

This saves the unnecessary instantiation of the model in `prepare.py` and `rebuild_manifest.py`.
Additionally this makes it easier to instantiate the datasets that we want using the `setup_dataset(config, split="blah")` syntax.

**Comment by mtauraso** [comment]
SGTM
