### ISSUE TITLE
Provide a fits manifest of all download attempts.

### ISSUE THREAD

**Issue by aritraghsh09** [lincc-frameworks/fibad#48]
**Feature request**

- Currently, the image download module returns images corresponding to the user-supplied fits table.  But, there needs to be a way for the user to know what the names of the returned cutout files are. Otherwise, if the user is placing the cutouts in a single common directory, it becomes difficult to keep track of the files. 

- This is especially important for users who are using the download module, without necessarily directly proceeding to the `fibad` analysis step. 

- I know users could map their fits tables to the downloaded file names using regex, but it would be nice to make this easier.

- My suggestion is to output a modified version of the user-supplied fits table with as many additional columns as the number of filters requested. Each filter column should contain the name of the downloaded file. 

- We can also consider incorporating the failed downloads into the above feature request by simply putting `NULL` or something similar for the file names where downloads failed. 

**Before submitting**
Please check the following:

- [X] I have described the purpose of the suggested change, specifying what I need the enhancement to accomplish, i.e. what problem it solves.
- [X] I have included any relevant links, screenshots, environment information, and data relevant to implementing the requested feature, as well as pseudocode for how I want to access the new functionality.
- [X] If I have ideas for how the new feature could be implemented, I have provided explanations and/or pseudocode and/or task lists for the steps.

**Comment by mtauraso** [comment]
A manifest would roughly look like a fits file with columns (object_id, ra, dec, tract, filter, filename) where the filename is null for downloads that failed.
